### ISSUE TITLE
Windows 10 Pro bug

### ISSUE THREAD

**Issue by Ogglas** [dejavusecurity/OutlookPrivacyPlugin#108]
Hello,

In Outlook 2013 (15.0.4753.1003 32-bit, part of Office 365) on Microsoft Windows 10 Pro, Version 10.0.10240 Build 10240 the plugin can not display emails. Everything looks great when I first try to open the email and the password prompt comes up as expected. However when the password has been entered all I can see is a blank email with attachments. It worked flawlessly on Windows 7 and 8.1 but something seems to differ with Windows 10. Is there anyway I can debug this?

**Comment by Baebeca** [comment]
same here after upgrading to Office 2010 Pro

**Comment by Strykar** [comment]
No issues yet with Outlook 2013 15.0.4763.1000 (part of Office Professional Plus) running on Windows 10 Pro.

**Comment by Baebeca** [comment]
Klepatra works also not fine in the effected installations.
I will try to fix Kleopatra in the first step

**Comment by Baebeca** [comment]
Problems found:
- AV Scanner Blocks Kleopatra in Startup
- Outlook has disabled the Plugin

No issue here

**Comment by Meddington** [comment]
@Ogglas When you upgraded to Win 10 did Office get reinstalled or was it the same office install that worked with OPP on Win8?  NOTE: Asking if this is the same install, not same version.

**Comment by Ogglas** [comment]
@Meddington Clean install of Office, upgraded to Windows 10 first thing when I got my new computer.

**Comment by Meddington** [comment]
Please attach %AppData%/OutlookPrivacyPlugin/log.txt

**Comment by mahaha** [comment]
I am having the same issue, though some emails open fine, and others just show a blank page.

**Comment by Meddington** [comment]
Is there anything different about the emails that don't display?  HTML vs. Plaintext.  ASCII vs. Unicode?  MIME vs. inline, etc.?

**Comment by mahaha** [comment]
There must be something, but all emails aren't encrypted by the sender, but by my own email server, so I can't really imagine what differences there could be. Strangely a common denominator between most emails I can't open seems to be that they were sent from Macs with Apple Mail. Not all were sent from Macs, but all the ones sent from Macs I cannot open. Not sure if this is any help.

**Comment by Meddington** [comment]
Well, differences in the plaintext, not cypher.

**Comment by Ogglas** [comment]
%AppData%/OutlookPrivacyPlugin/log.txt

As @mahaha mentioned nothing gets logged when an email opens blank @Meddington. Copied the log file anyway.

```
-------- 2015-10-08 08:53:08 --------
DecryptAndVerify

Deja.Crypto.BcPgp.SecretKeyNotFoundException: Error, unable to locate decryption key.
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptHandlePgpObject(PgpObject obj)
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptAndVerify(Byte[] data, Boolean ignoreIntegrityCheck)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.DecryptAndVerify(String to, Byte[] data, CryptoContext& outContext)
-------- 2015-10-08 08:53:28 --------
DecryptAndVerify

Deja.Crypto.BcPgp.SecretKeyNotFoundException: Error, unable to locate decryption key.
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptHandlePgpObject(PgpObject obj)
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptAndVerify(Byte[] data, Boolean ignoreIntegrityCheck)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.DecryptAndVerify(String to, Byte[] data, CryptoContext& outContext)
-------- 2015-10-08 08:57:40 --------
DecryptAndVerify

Deja.Crypto.BcPgp.SecretKeyNotFoundException: Error, unable to locate decryption key.
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptHandlePgpObject(PgpObject obj)
   at Deja.Crypto.BcPgp.PgpCrypto.DecryptAndVerify(Byte[] data, Boolean ignoreIntegrityCheck)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.DecryptAndVerify(String to, Byte[] data, CryptoContext& outContext)
```
