### ISSUE TITLE
Failure to find senders SMTP address

### ISSUE THREAD

**Issue by Chewie9999** [dejavusecurity/OutlookPrivacyPlugin#110]
I was trying to reply to a message and encrypt it.
The plugin found the key in my key store (once i'd imported it successfully), but it came up with the following error:

---------------------------
Outlook Privacy Error
---------------------------
The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()

   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)

   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
---------------------------
OK   
---------------------------

I'm using the BETA 49 of the plugin, with Outlook 15.0.4753.1002 connected to O365.
Please let me know if you need any more details.

**Comment by Meddington** [comment]
Please attach %AppData%/OutlookPrivacyPlugin/log.txt

**Comment by Chewie9999** [comment]
Hi Meddington.
Sorry, I don't have write permission to this repository.
Below is a paste of the log. Hope it's readable:


-------- 09/10/2015 10:31:55 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 10:35:38 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 10:37:27 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 10:37:50 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 10:57:22 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 10:57:35 --------
Application_ItemSend

System.Runtime.InteropServices.COMException (0x80004005): The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
-------- 09/10/2015 11:02:15 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 11:02:25 --------
Application_ItemSend

System.Runtime.InteropServices.COMException (0x80004005): The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
-------- 09/10/2015 11:02:39 --------
Application_ItemSend

System.Runtime.InteropServices.COMException (0x80004005): The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
-------- 09/10/2015 11:02:52 --------
Application_ItemSend

System.Runtime.InteropServices.COMException (0x80004005): The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
-------- 09/10/2015 11:04:50 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)
-------- 09/10/2015 11:05:06 --------
Application_ItemSend

System.Runtime.InteropServices.COMException (0x80004005): The operation failed.
   at Microsoft.Office.Interop.Outlook.AddressEntry.GetExchangeUser()
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.GetSMTPAddress(MailItem mailItem)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.Application_ItemSend(Object Item, Boolean& Cancel)
-------- 16/10/2015 09:49:03 --------
VerifyEmail

System.Runtime.InteropServices.COMException (0x8004010F): The property "http://schemas.microsoft.com/mapi/string/{4E3A7680-B77A-11D0-9DA5-00C04FD65685}/Internet Charset Body/0x00000102" is unknown or cannot be found.
   at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookPrivacyPlugin.OutlookPrivacyPlugin.HandlePgpMime(MailItem mailItem, Attachment encryptedMime, Attachment sigMime, String sigHash)

**Comment by Meddington** [comment]
I've added a change that may fix this. It will be in BETA 52.

**Comment by Meddington** [comment]
I've added a possible fix that will be included in BETA 52

**Comment by Chewie9999** [comment]
Thanks, looks much better :)
